### ISSUE TITLE
[Bug] Checking update SHOULD NEVER cut down the CLI process even though failed

### ISSUE THREAD

**Issue by TinyChou** [hxfdarling/a8k#26]
as shown:

![image](https://user-images.githubusercontent.com/4263842/59732322-60d9d780-927c-11e9-9a55-9f527d5d3b08.png)

**Comment by TinyChou** [comment]
We should ignored it when errors thrown.

**Comment by hxfdarling** [comment]
Which version?

**Comment by hxfdarling** [comment]
You need uninstall imt-cli. And install a8k module
