### ISSUE TITLE
使用a8k create时候报错

### ISSUE THREAD

**Issue by kenzung** [hxfdarling/a8k#27]
**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/6317307/61261042-08322780-a7b3-11e9-8a13-926112f36de6.png)
提示需要安装@a8k/plugin-typescript-template
**Describe the solution you'd like**
建议集成到a8k库，或者直接在文档中添加指引
**Describe alternatives you've considered**

**Additional context**

**Comment by hxfdarling** [comment]
你是用的是什么版本？你可以通过 `k --version ` 获取但本号

**Comment by hxfdarling** [comment]
你好，你可以通过`npm i -g a8k@beta` 安装最新版本解决这个问题。我将会修复1.x版本的问题
