### ISSUE TITLE
`lerna bootstrap` missing many dependencies in lerna root

### ISSUE THREAD

**Issue by TinyChou** [hxfdarling/a8k#28]
**Describe the bug**
Steps to produce the bug:

1. git clone https://github.com/hxfdarling/a8k.git
2. npm run bootstrap
3. npm run dev

**Expected behavior**
No errors for all the dependencies.

**Screenshots**
![image](https://user-images.githubusercontent.com/4263842/63736725-b18e3200-c8b6-11e9-8297-3045c6a031b5.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by TinyChou** [comment]
May be u has been hoisted external dependencies using:

`lerna bootstrap --hoist`

But newcomers should NOT try it with current script `lerna bootstrap --no-ci`

**Comment by hxfdarling** [comment]
Have you executed `npm i`?

**Comment by hxfdarling** [comment]
May be u can executed `npx lerna clean` &&`rm -rf node_modules` && `npm i ` && `npm run bootstrap` to fix.?

**Comment by TinyChou** [comment]
yep , i can `npm i` to solve the problem.

**Comment by TinyChou** [comment]
maybe we should have a development guide to tell guys how to do it

**Comment by TinyChou** [comment]
> yep , i can `npm i` to solve the problem.

also, i can run `lerna bootstrap --hoist`

**Comment by hxfdarling** [comment]
可以提个pr么？


在 2019年8月27日，19:36，Tiny Chou <notifications@github.com> 写道：

﻿

Closed #28<https://github.com/hxfdarling/a8k/issues/28>.
