### ISSUE TITLE
Scripts will be all injected to <head/> by default

### ISSUE THREAD

**Issue by TinyChou** [hxfdarling/a8k#29]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by TinyChou** [comment]
https://github.com/hxfdarling/a8k/blob/f1da293f1084b592e61668698286451efeff137d/packages/a8k/src/plugins/config-html.ts#L49

`html-webpack-plugin` with options _inject: 'head'_ which is solid by default and developer can not override it.

**Comment by hxfdarling** [comment]
It is not recommended to override it, because the defer mode is used, which allows the browser to parse external resources as early as possible.

**Comment by hxfdarling** [comment]
you can use `chain.plugin.xxx.tap` to modify options

```js
Object.keys(entry).forEach(key => {
        chainConfig
          .plugin(`HtmlWebpackPlugin-${key}`)
          .tap(args => [{...args[0], inject: false}])
          .end();
      });
```
